[tox]
envlist = qa,py39,py310,py311,pypy3
isolated_build = True

[testenv]
deps =
    mypy
extras =
    test
commands =
    pytest -vv {posargs:tests}
    mypy {posargs:flagger tests}

[testenv:uv]
skip_install = true
deps =
commands =
    uv run --with pytest pytest -vv {posargs:tests}

[testenv:qa]
skip_install = true
deps =
    pycodestyle
    pyflakes
commands =
    pyflakes {posargs:flagger tests}
    pycodestyle {posargs:flagger tests}

[testenv:upload]
skip_install = true
deps =
    build
    twine
commands =
    python -m build -s -w
    twine upload dist/*
